version: "3.7"

services:
  web:
    build: .
    container_name: ai_dashboard_web
    environment:
      DEBUG: "True"
      SECRET_KEY: ${SECRET_KEY}
      SQLITE_PATH: /app/data/db.sqlite3
      HF_HOME: /app/.cache/huggingface
      TRANSFORMERS_CACHE: /app/.cache/huggingface/transformers
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
      - staticfiles:/app/staticfiles
      - hf_cache:/app/.cache/huggingface
    command: ["/app/entrypoint.sh"]
    restart: unless-stopped

volumes:
  sqlite_data: {}
  staticfiles: {}
  hf_cache: {}